namespace :site do
	desc "minifies css and js and outputs to min folder"
		task :minify do
			puts "Minifying => CSS"
			system("juicer merge --force foundation/stylesheets/forms.css foundation/stylesheets/globals.css foundation/stylesheets/grid.css foundation/stylesheets/mobile.css foundation/stylesheets/orbit.css foundation/stylesheets/reveal.css foundation/stylesheets/typography.css foundation/stylesheets/ui.css css/style.css -o min/min.css >> _minify.log")
			puts "Minifying => IE CSS"
			system("juicer merge --force foundation/stylesheets/ie.css -o min/min-ie.css >> _minify.log")
			puts "Minifying => JS"
			system("juicer merge --force -i foundation/javascripts/jquery.min.js foundation/javascripts/forms.jquery.js foundation/javascripts/jquery.customforms.js foundation/javascripts/jquery.orbit-1.3.0.js foundation/javascripts/jquery.placeholder.min.js foundation/javascripts/jquery.reveal.js -o min/min.js >> _minify.log")
		end
		task :preview do
			puts "Starting Jekyll server with auto-reloading"
			system("jekyll --server --auto")
		end
end
